<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('companies')->insert([
            [
                'name' => 'PT. Lesin Aja Edukasi Indonesia',
                'address' => 'Jl. Graha Kuncara No.22 Blok L, Kemiri, Kec. Sidoarjo, Kabupater Sidoarjo, Jawa Timur 61234',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/lesin.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IT Brain',
                'address' => 'Perum Graha Kuncara No.29 Blok H, Kemiri, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur 61234',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/itbrain.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CV. Hexa Integra Mandiri Sidoarjo',
                'address' => 'Kompleks Balai RW Jl. Bukit Kismadani III No.13, Dusun Tegal Gn., Bluru Kidul, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur 61233',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/hexa.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Kama Jaya Fortuna',
                'address' => 'Pergudangan Tanrise Southgate, Blok A7, Dusun Sruni, Sruni, Gedangan, Sidoarjo Regency, East Java 61254',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/kama.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Importa Jaya Abadi Jakarta',
                'address' => 'Pergudangan Tanrise Southgate, Blok A33, Dusun Sruni, Sruni, Gedangan, Sidoarjo Regency, East Java 61254',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/importa.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Antariksa Nusantara Indonesia Group',
                'address' => 'Pergudangan Safe N Lock Blok AR, Jalan Lingkar Timur, Pucang anom. Kec. Sidoarjo, Kab. Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/antariksa.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT Insera Sena Polygon',
                'address' => 'Jl. Jawa No.393 Binangun, Wadungasih, Kec. Buduran, Kabupaten Sidoarjo, Jawa Timur 61252',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/insera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT Trimitra Sejati Jaya',
                'address' => 'Komple Pergudangan dan Industri Permata Gedangan Blok AD No 1 Bohar Taman Sidoarjo Jawa Timur 61257, Indonesia',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/trimitra.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. BPR Buduran Deltapurnama',
                'address' => 'Jalan Garuda No.06, Buduran, Kec Buduran, Kabupaten Sidoarjo, Jawa Timur 61252',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bpr.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Karya Indah Medika',
                'address' => 'Komplek Pergudangan Sinar Buduran Jalan Lingkar Timur, Prasungtani, Prasung, Kec. Buduran, Kabupaten Sidoarjo, Jawa Timur 61252',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Japfa Comfeed',
                'address' => 'Jl. HRM. Mangundiprojo, Banarmelati, Banjarkemantren, Kec. Buduran, Kab. Sidoarjo, Jawa Timur',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/japfa.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Atlas Trasindo Raya',
                'address' => 'Jl. Raya Daan Mogot KM.10 No.22 jakarta Barat',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/atlas.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],


             [
                'name' => 'Dinas Sosial Kabupaten Sidoarjo',
                'address' => 'Jl.Pahlawan No.45 Jetis, Jati, Kec.Sidoarjo, Kabupaten Sidoarjo Jawa Timur 61226',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Badan Pelayanan Pajak Daerah Sidoarjo',
                'address' => 'Jl. Pahlawan No.56 Jetis, Lemahputro Kec. Sidoarjo, Kab. Sidoarjo Jawa Timur 61212',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bppd.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Badan Pengawas keuangan dan Pembangunan',
                'address' => 'Jl. Raya Bandara Juanda, Semawalang, Semambung, Kec. Gedangan, Kabupaten Sidoarjo, Jawa Timur 61254',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bpkp.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinas Koperasi dan UMKM Provinsi Jawa Timur',
                'address' => 'Jl. Raya Juanda No. 22, Sawotratap, Gedangan, Semalang, Semambung, Kec. Gedangan, Surabaya, Jawa Timur 61254',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/dinaskoperasi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinas PU Bina Marga dan Sumber Daya Air',
                'address' => 'Jl. Sultan Agung No.17A, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/dinaspu.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BPR Tulangan Dasa Nusantara',
                'address' => 'Jl. Raya Larangan',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bprtulangan.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CV. Makmur Abadi',
                'address' => 'Perum Bukit Kismadani, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/makmur.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EBAD Wisata',
                'address' => 'Juanda Business Center No.1 A8-A9, Dusun Pager, Sawotratap, Kec. Gedangan, Kab. Sidoarjo, Jawa Timur 61254',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/ebad.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Story Space Studio',
                'address' => 'Ruko Natura Square 2 EE/6, Siwalanpanji, Kab. Sidoarjo, Jawa Timur 61252',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/story.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CV. Xpesindo Logistik Utama',
                'address' => 'Pergudangan Safe Lock Lingkar Timur',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/express.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Polresta Sidoarjo',
                'address' => 'Jl. Raya Cemengkalang, No.12, Cemengkalang, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61234',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/polisi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hayai Studio',
                'address' => 'Jl. Jenggolo No.2 A, Badrek, Siwalanpanji, Kec. Buduran, Kab. Sidoarjo, Jawa Timur 61219',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/hayai.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'name' => 'CV. Kasa Edtrains Kahuripan',
                'address' => 'Perum Kahuripan Nirwana Blok CA 3 No.27',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Contrast Digital Printing',
                'address' => 'Ruko Graha Niaga blok B 18 - 19, Buduran Sidoarjo, Jawa Timur 61252',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/contrast.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kantor Kecamatan Sidoarjo',
                'address' => 'Jl. Pahlawan No.1 RW.6 Sidokumpul, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61212',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BPR Candi Saka Artha',
                'address' => 'Jl. Raya Gelam No.10, Kec. Candi, Kab. Sidoarjo, Jawa Timur 61271',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bpr.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lippo Plaza Sidoarjo',
                'address' => 'Jl. Jati Raya No.1 Jati, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61271',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/lippo.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cahaya Printing',
                'address' => 'Jl. Raya Sepande, No.18, RT.05 RW.02, Gading Fajar Sepande, Candi, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/cahaya.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Pegadaian Cabang Gedangan',
                'address' => 'Jl. KH. Mukmin No.6, Kec. Gedangan, Kab. Sidoarjo, Jawa Timur 61254',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/pegadaian.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hotel Luminor',
                'address' => 'Jl. Pahlawan, jetis, Lemahputro, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61213',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/luminor.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fave Hotel Sidoarjo',
                'address' => 'Jl. Jenggolo No.15, Pucang Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/favehotel.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bank BTN',
                'address' => 'Jl. Ahmad Yani No.15, RW.1, Sidokumpul, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61212',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/btn.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BRI Sidoarjo',
                'address' => 'Jl. Ahmad Yani 35, Sidokumpul, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61212',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bri.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CV Euforia Garment',
                'address' => 'Jl. Yos Sudarso, No.104, Sidoklumpuk, Sidokumpul, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61219',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/euforia.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],




            [
                'name' => 'PT. Gema Solusindo Utama',
                'address' => 'Taman Dhika Blok D19, Cluster Bromo Sidokerto, Buduran Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/gama.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BPR Mitra Majujaya Mandiri',
                'address' => 'Jl. Raya Kenogno No.54, Kec. Tulangan, Kab. Sidoarjo, Jawa Timur 61273',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bpr.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Piramid Group - Piramid Kebab',
                'address' => 'Istana Mentari Suko, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61224',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/piramid.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Lillah Rizqi Berkah',
                'address' => 'Puri Indah f-i No.55H, Sungon, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61224',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KPP Madya Juanda Sidoarjo',
                'address' => 'Jl. Raya Bandara Juanda No.37, Semambung, Kec. Gedangan, Kab. Sidoarjo, Jawa Timur 61254',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/djp.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Pegadaian Cabang Sidoarjo',
                'address' => 'Jl. Mojopahit No.116, Sidowayah, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61215',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/pegadaian.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinas Tenaga Kerja Kabupaten Sidoarjo',
                'address' => 'Jl. Raya Jati No.4, Babatan, jati, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur, 61226',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/dinaskerja.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pikaler Creative Studio',
                'address' => 'Terrania Living Blok NB05, Kloposepuluh, Sukodono, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CV. Faiz Jaya',
                'address' => 'Puri Indah No. R-17, Suko, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61224',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/faiz.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Galang Sukses Bersama',
                'address' => 'Perum Puri Surya Jaya, Cluster Osaka Blossom Aiko Blok OB2, No,02 Gedangan',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PDAM Delta Tirta',
                'address' => 'Jl. Pahlawan No.1 RW.06, Sidokumpul, Kab. Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/pdam.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lim Corporation',
                'address' => 'Jl. Perum Prima Garden Estate No.07-01 Klagen, Kebonagung, Kec. Sukodono, Kab. Sidoarjo, Jawa Timur 61258',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/lim.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'name' => 'New Idea Indonesia',
                'address' => 'Jl. Kebonagung Sukodono, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/new.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ageless Clinic',
                'address' => 'Ruko Graha Mutiara Blok C-3 Jl. Diponegoro, No.12, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/ageless.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Altama Teko Mandiri',
                'address' => 'Perumahan Wahyu Taman Sarirogo Blok AS-36, Sidoarjo',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Paco Amplas Indonesia',
                'address' => 'Gedangan Pergudangan Meiko Abadi D-20, 61254, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/paco.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jago Cetak ID',
                'address' => 'Jl. Gadung No.5 Wage, Taman, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/jago.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Sejahtera Dunia Akhirat Limawaktu Group',
                'address' => 'Jl.Brigjend Katamso No.37-39, Mekar Jaya, Binangun, Waru, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sejahtera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bank Jatim Cabang Gedangan',
                'address' => 'Jl. A. Yani No.119, Magersari, Kec. Gedangan, Kab. Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/jatim.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Sekawan Cosmetic',
                'address' => 'Jalan Lingkar Timur No.183, Dusun Rangkah Lor Bluru Kidul, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 6123',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sekawan.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rumah Budaya Sidoarjo',
                'address' => 'Jl. Malik Ibrahim No.39, Pucanganom, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/rumah.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KSPPS Ar Rohmah Jatim - Candi',
                'address' => 'Perum Mutiara Prima Raya Blok A No.06, Candi',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/ksps.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'S & R Consultant Jati Sidoarjo',
                'address' => 'Banjarbendo, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61225',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinas Komunikasi dan Informatika',
                'address' => 'Jl. Diponegoro No.139, Lemah Putro, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61213',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/kominfo.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'name' => 'Hugo Pictures',
                'address' => 'Pesona Permata Gading 2, Bluru Kidul, Kab. Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/hugo.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Foto Produk Kita.id',
                'address' => 'Perum The Taman, Dhika Cluster Wilis Blok F, No.07, Sono, Buduran, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/foto.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KISHA Accounting And Management Support',
                'address' => 'Perum Sentosa Residence Blok 4 No. 24, Modong, RT.06, RW.01, Kec. Tulangan',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/kisha.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Adigi Perkasa Digital Printing',
                'address' => 'Graha Kota No. A12-02, Sungon, Suko, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/adigi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Mentari Setya Perkasa',
                'address' => 'Perum Puri Indah Lestari FM-02 Suko, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/mentari.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Metropolitan Bayutama',
                'address' => 'Komplek Hotel Istana Permata No. 307, Jl. Raya Juanda',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/metropolitan.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BKD Kabupaten Sidoarjo',
                'address' => 'Jl. Mojopahit, No.05, Larangan , Candi, Sidoarjo 61271',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bkd.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Koperasi Delta Wiyata',
                'address' => 'Jl. Pondok Jati, Blok A1, No.08 Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/koperasi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GIGA Corporation Premia Karya Sukodono',
                'address' => 'Jl. Raya Sukodono, No.17, Sambang, Kebonagung, Sukodono, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/giga.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '35mm.camstudio',
                'address' => 'Istana Mentari Blok A2, No.4 Cemeng Kalang, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/35.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Jagoan Digital Indonesia (JDI)',
                'address' => 'Osaka Blossom OB 2/19 Puri Surya Jaya Gedangan',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/jagoan.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Ramayana Lestari Sentosa, Tbk.',
                'address' => 'Jl. Gajah Mada No.120, Lemahputro, Daleman, Pekauman, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61213',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/ramayaana.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'name' => 'Dharma Plus',
                'address' => 'Perumahan Kahuripan Nirwana Blok CB 12, No.2 Sumput, Kec. Sidoarjo, Kab. Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kecamatan Gedangan',
                'address' => 'Jl. Raya Gedangan',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. BPR Buduran Deltapurnama',
                'address' => 'Jl. Garuda Buduran Sidoarjo No.06',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bpr.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinas Perijinan Penanaman Modal',
                'address' => 'Jl. Pahlawan No.141, Jetis, Lemahputro, Kec. Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/dinasperijinan.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kecamatan Candi',
                'address' => 'Jl. Moch Ridwan No.01 Gelam, Kec. Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Indraco (Suncity)',
                'address' => 'Jl. Pahlawan, No.01 Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/suncity.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Markaz Design',
                'address' => 'Jl. Jati Selatan III No.20, RT002/RW002, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/markaz.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Rukun Jaya Kompak',
                'address' => 'Jl. Raya Sukodono, No.500, Keboananom Gedangan, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kantor Pelayanan Pajak Pratama Sidoarjo Utara',
                'address' => 'Jl. Pahlawan No.55, Jetis, Lemahputro, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur 61213',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/djp.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kejaksaan RI Kejaksaan Tinggi Jawa Timur',
                'address' => 'Jl. Sultan Agung N0.36, Sidokumpul, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/kejaksaan.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bank Jatim Cabang Sidoarjo',
                'address' => 'Jl. A. Yani, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/jatim.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinas Perumahan dan Pemukiman Sidoarjo',
                'address' => 'Jl. A. Yani Pucang, Sidokumpul Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'name' => 'PT. Toyota Asri Lestari',
                'address' => 'Jl. Pucang Anom Tim. No.7, Kertajaya, Kec. Gubeng, Surabaya, Jawa Timur 60282',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/toyota.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Trusted Zone Brand Identity',
                'address' => 'Ruko Alam Juanda Blok RK 2, No. 23, Tani Nelayan, Pepe, Sedati, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/trusted.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lokatara Karya Indonesia',
                'address' => 'Puri Surya Jaya Taman Nagoya Blok G9 / 09, Sidoarjo',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/lokatara.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bank Jatim Cabang  Krian',
                'address' => 'Jl. Imam Bonjol No. 30, Kec. Krian Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/jatim.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bank Jatim Cabang  Prambon',
                'address' => 'Jl. Diponegoro No. 123 Kec. Prambon Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/jatim.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinas Kependudukan dan Pencatatan Sipil kabupaten Sidoarjo',
                'address' => 'Jl. Sultan Agung No. 23, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BANK DANA RAYA',
                'address' => 'PASAR LARANGAN',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/danaraya.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shafira Tour and Travel',
                'address' => 'Jl. Juanda I Blok 1-5, Sawotratrap, Kecamatan Gedangan',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/shafiraa.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kenzie Studio',
                'address' => 'Siwalanpanji, Buduran, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/kenziee.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kelurahan Cemengkalang',
                'address' => 'Jl. Raya Cemengkalang',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kecamatan Buduran',
                'address' => 'Jl. H. R. Moch. Mangundiprojo No. 270, Banjarkemantren, Buduran, Jambe, Banjarkemantren, Kec. Buduran',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinas Lingkungan Hidup dan Kebersihan Kabupaten Sidoarjo',
                'address' => 'Jl. Raya Siwalanpanji No. 36 Bedrek, Siwalanpanji Kec. Buduran',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/dlhk.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'name' => 'Desainme',
                'address' => 'l. A.Yani RT 12 RW 04 Gang 26 Medaeng Wetan, Waru, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/desainme.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Satria Persada Bersama',
                'address' => 'Jl. Delta Asri No.86, Ngingas, Kec. Waru, Sidoarjo.',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/satria.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CV. BINTANG KARYA CONSULTAN',
                'address' => 'Jl. Gebang Raya, AJ. 01 Sidoarjo',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Badan Perencanaan Pembangunan Daerah',
                'address' => 'Jl. Sultan Agung No.13, Gajah Timur, Magersari',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bappeda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DIC Creative',
                'address' => 'Sukodono - Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KSPPS AR ROHMAH JATIM - TAMAN',
                'address' => 'Jalan Taman Barat No. 59 ',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/ksps.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pollar Project',
                'address' => 'Ruko Center Point, Jl. Raya Lebo No. 21, Salam, Suko, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/polar.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT . Varia Usaha Beton',
                'address' => 'The Royal Business Park, Jl. Tambak Oso Jl. H. Anwar Hamzah No.F03 Blok F02, Kp. Baru, Tambakoso, Kec. Waru, Kabupaten Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/varia.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. ALAM DIANRAYA',
                'address' => 'Jln. Brebek Industri III No. 7 -11 , Brebek Industri , Brebek Kec. Waru ',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/alam.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. Binar Inovasi Digital - Mars Coding',
                'address' => 'Jl. Imam Bonjol Dusun No.3, RT.6/RW.2, Prumpon, Suruh, Sukodono, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/mars.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT Jawa Pos Media Televisi (JTV)',
                'address' => 'Jl. Ahmad Yani No. 88 Ketintang, Gayungan, Surabaya',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/jtv.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. BISI International Tbk.',
                'address' => 'Jl. Raya Surabaya - Mojokerto Km. 19, Bringinbendo, Sepanjang, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/bisi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'name' => 'CV Keoto Sarirogo Gemilang',
                'address' => 'Jl.Raya Sarirogo, Ruko citra city residen Block R- 9',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Intinity Picture',
                'address' => 'Jaya Maspion Permata Cluster Beryl B5/18, Gedangan, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master Racing Industries',
                'address' => 'Jl. Gadung No.8, Margomulyo, Wage, Kec. Taman, Kabupaten Sidoarjo, Jawa Timur 61257',
                'website' => null,
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/master.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bank Jatim Cabang Waru',
                'address' => 'Jl. Raya Tropodo No.110, Kec. Waru Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/jatim.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CV. Berkah Media Jaya',
                'address' => 'Jalan Rajawali No 26 Desa Punggul, Kec. Gedangan, Kabupaten Sidoarjo, Jawa Timur 61254',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/berkah.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KOPERASI DEPAG MINIMARKET',
                'address' => 'Jl. Monginsidi No.3, Sidoklumpuk, Sidokumpul, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur 61218',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/koperasi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ADIRA FINANCE',
                'address' => 'Jl. HANG TUAH NO 2 SIDOARJO',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/noimg.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spoor.Photo',
                'address' => 'Jl. Balai Desa RW 05 RT 18 No 01 Candi, Candi Sayang, Candi, Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/spoor.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT.SARI BHUANA NUSAJAYA',
                'address' => 'Taman Pinang Indah Blok GV / 25 SDA',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/sari.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aluna Booth Indonesia',
                'address' => 'Jl. Mangga II Jl. Tanggulangin Asri blok P-18, Kalitengah, Kec. Tanggulangin, Kabupaten Sidoarjo, Jawa Timur 61272',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/aluna.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PT. HISANA SIDOARJO ',
                'address' => 'Jl. Suko Legok III No.9 Sukodono Sidoarjo, Dusun Legok, Suko, Kec. Sukodono, Kabupaten Sidoarjo',
                'website' => '',
                'logo' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/company/hisana.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}
