<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class NewsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('news')->insert([
   [
        'title' => 'Selamat! ananda Rafqa Pietra Juara 2 Lomba Vlog Universitas Brawijaya',
        'description' => 'Prestasi membanggakan dari siswa SMKN 2 Buduran, Rafqa Pietra berhasil meraih Juara 2 dalam Lomba Vlog yang diselenggarakan oleh Universitas Brawijaya. Karya kreatif yang ditampilkan mendapat apresiasi tinggi dari para juri dan menjadi inspirasi bagi siswa-siswa lainnya.',
        'slug' => Str::slug('Selamat! ananda Rafqa Pietra Juara 2 Lomba Vlog Universitas Brawijaya'),
        'published_at' => '2025-08-15 10:30:00',
        'category_id' => 3, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news6.jpg',
        'content' => 'Rafqa Pietra, siswa SMKN 2 Buduran, berhasil meraih Juara 2 dalam kompetisi Vlog yang diselenggarakan Universitas Brawijaya. Karya kreatifnya diapresiasi oleh juri dan menjadi inspirasi bagi siswa lain untuk berkarya.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Selamat! Dinda Dwi Wulandari Juara 1 Karate Provinsi Jawa Timur',
        'description' => 'Prestasi membanggakan dari siswi SMKN 2 Buduran, Dinda Dwi Wulandari yang berhasil meraih Juara 1 dalam kejuaraan Karate tingkat Provinsi Jawa Timur. Pencapaian ini menjadi kebanggaan sekolah dan memotivasi siswa lain untuk terus berprestasi di bidang olahraga.',
        'slug' => Str::slug('Selamat! Dinda Dwi Wulandari Juara 1 Karate Provinsi Jawa Timur'),
        'published_at' => '2025-09-09 10:30:00',
        'category_id' => 3, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news3.jpg',
        'content' => 'Dinda Dwi Wulandari, siswi SMKN 2 Buduran, berhasil meraih Juara 1 dalam kejuaraan Karate tingkat Provinsi Jawa Timur. Prestasi ini menjadi kebanggaan bagi sekolah dan memotivasi siswa lain untuk terus berprestasi.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Gubernur Khofifah Beri Apresiasi Kepala SMK Negeri 2 Buduran',
        'description' => 'Gubernur Jawa Timur, Khofifah Indar Parawansa, memberikan apresiasi khusus kepada Kepala SMKN 2 Buduran atas kepemimpinannya yang berhasil meningkatkan mutu pendidikan dan berbagai prestasi sekolah. Apresiasi ini diberikan dalam kunjungan resmi gubernur ke sekolah.',
        'slug' => Str::slug('Gubernur Khofifah Beri Apresiasi Kepala SMK Negeri 2 Buduran'),
        'published_at' => '2025-03-05 10:30:00',
        'category_id' => 3, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news7.jpg',
        'content' => 'Dalam kunjungannya, Gubernur Jawa Timur Khofifah Indar Parawansa memberikan apresiasi atas kepemimpinan Kepala SMKN 2 Buduran yang dinilai berhasil meningkatkan mutu pendidikan dan berbagai prestasi sekolah.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Alhamdulillah Mohammad Rifal Al Fahri XII RPL SMKN 2 Buduran meraih Juara 3 IT SOFTWARE SOLUTIONS FOR BUSINESS',
        'description' => 'Prestasi membanggakan kembali diraih oleh siswa SMKN 2 Buduran. Mohammad Rifal Al Fahri dari jurusan RPL kelas XII berhasil meraih Juara 3 dalam kompetisi IT Software Solutions for Business tingkat nasional, membuktikan keunggulan pendidikan teknologi di sekolah ini.',
        'slug' => Str::slug('Alhamdulillah Mohammad Rifal Al Fahri XII RPL SMKN 2 Buduran meraih Juara 3 IT SOFTWARE SOLUTIONS FOR BUSINESS'),
        'published_at' => '2025-04-26 10:30:00',
        'category_id' => 3, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news8.jpg',
        'content' => 'Prestasi membanggakan kembali diraih siswa SMKN 2 Buduran. Mohammad Rifal Al Fahri dari jurusan RPL kelas XII berhasil meraih Juara 3 dalam kompetisi IT Software Solutions for Business tingkat nasional.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Prestasi Keagamaan dari KEMENAG untuk SMKN 2 Buduran',
        'description' => 'Kementerian Agama Republik Indonesia memberikan penghargaan bergengsi kepada SMKN 2 Buduran atas berbagai prestasi keagamaan yang diraih oleh para siswanya. Penghargaan ini diharapkan dapat memotivasi siswa untuk terus meningkatkan keimanan dan prestasi spiritual mereka.',
        'slug' => Str::slug('Prestasi Keagamaan dari KEMENAG untuk SMKN 2 Buduran'),
        'published_at' => '2025-09-12 10:30:00',
        'category_id' => 3, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news10.jpg',
        'content' => 'SMKN 2 Buduran menerima penghargaan dari Kementerian Agama atas berbagai prestasi keagamaan yang diraih oleh para siswanya. Penghargaan ini diharapkan memotivasi siswa untuk terus meningkatkan keimanan dan prestasi spiritual.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Tim CHEERLEADERS SMKN 2 Buduran (Team Cheer All Girl Premier Senior) meraih Juara Runner Up 2 Kejurnas 2025',
        'description' => 'Prestasi gemilang diraih oleh Tim Cheerleaders SMKN 2 Buduran dalam kategori Team Cheer All Girl Premier Senior yang berhasil meraih posisi Runner Up 2 pada Kejuaraan Nasional 2025. Tim yang penuh semangat ini membuktikan dedikasi dan kerja keras mereka dalam olahraga cheerleading.',
        'slug' => Str::slug('Tim CHEERLEADERS SMKN 2 Buduran (Team Cheer All Girl Premier Senior) meraih Juara Runner Up 2 Kejurnas 2025'),
        'published_at' => '2025-09-12 10:30:00',
        'category_id' => 3, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news11.jpg',
        'content' => 'Tim Cheerleaders SMKN 2 Buduran dalam kategori Team Cheer All Girl Premier Senior berhasil meraih posisi Runner Up 2 pada Kejuaraan Nasional 2025. Prestasi ini menunjukkan dedikasi dan kerja keras tim dalam mengembangkan bakat di bidang cheerleading.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Selamat! Lintang Permata Zaman, Juara 3 FLS3N Komik Digital Tk. Prov. JATIM',
        'description' => 'Siswa berbakat SMKN 2 Buduran, Lintang Permata Zaman, berhasil meraih Juara 3 dalam kompetisi FLS3N (Festival Literasi Siswa dan Seni Nasional) kategori Komik Digital tingkat Provinsi Jawa Timur. Prestasi ini menunjukkan kemampuan kreatif siswa dalam bidang seni digital dan literasi.',
        'slug' => Str::slug('Selamat! Lintang Permata Zaman, Juara 3 FLS3N Komik Digital Tk. Prov. JATIM'),
        'published_at' => '2025-09-12 10:30:00',
        'category_id' => 3, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news12.jpg',
        'content' => 'Lintang Permata Zaman, siswa SMKN 2 Buduran, berhasil meraih Juara 3 dalam kompetisi FLS3N kategori Komik Digital tingkat Provinsi Jawa Timur. Prestasi ini menunjukkan kemampuan kreatif siswa dalam bidang seni digital dan literasi.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Penghargaan dari Kakemenag untuk menjadi Piloting PROJECT PAIS BERKARAKTER jenjang SMA/SMK/SLB/MAN Jawa Timur',
        'description' => 'SMKN 2 Buduran mendapat kehormatan menerima penghargaan dari Kantor Kementerian Agama (Kakemenag) untuk menjadi sekolah piloting dalam Project PAIS Berkarakter untuk jenjang SMA/SMK/SLB/MAN di Jawa Timur. Program ini bertujuan untuk mengembangkan pendidikan agama Islam yang berkarakter.',
        'slug' => Str::slug('Penghargaan dari Kakemenag untuk menjadi Piloting PROJECT PAIS BERKARAKTER jenjang SMA/SMK/SLB/MAN Jawa Timur'),
        'published_at' => '2025-09-12 10:30:00',
        'category_id' => 3, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news13.jpg',
        'content' => 'SMKN 2 Buduran mendapat kehormatan menjadi sekolah piloting dalam Project PAIS Berkarakter untuk jenjang SMA/SMK/SLB/MAN di Jawa Timur. Program ini bertujuan untuk mengembangkan pendidikan agama Islam yang berkarakter dan berakhlak mulia.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Hebat! Grup Banjari Siswa SMKN 2 Buduran Meraih Juara 2',
        'description' => 'Prestasi membanggakan dalam bidang seni islami diraih oleh Grup Banjari siswa SMKN 2 Buduran yang berhasil meraih Juara 2 dalam kompetisi tingkat regional. Pencapaian ini menunjukkan kemampuan siswa dalam melestarikan seni tradisional islami dan mengembangkan bakat di bidang musik religi.',
        'slug' => Str::slug('Hebat! Grup Banjari Siswa SMKN 2 Buduran Meraih Juara 2'),
        'published_at' => '2025-09-12 10:30:00',
        'category_id' => 3, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news14.jpg',
        'content' => 'Grup Banjari siswa SMKN 2 Buduran berhasil meraih Juara 2 dalam kompetisi tingkat regional. Prestasi ini menunjukkan kemampuan siswa dalam melestarikan seni tradisional islami dan mengembangkan bakat di bidang musik religi.',
        'created_at' => now(),
        'updated_at' => now(),
    ],




    [
        'title' => 'Kunjungan SMKN JENAWI JATENG ke SMKN 2 BUDURAN',
        'description' => 'Kegiatan silaturahmi dan kunjungan kerja dari SMKN Jenawi Jawa Tengah ke SMKN 2 Buduran dalam rangka mempererat hubungan antar sekolah kejuruan. Program ini bertujuan untuk berbagi pengalaman dalam pengembangan kurikulum, manajemen sekolah, serta inovasi pembelajaran di bidang kejuruan untuk meningkatkan kualitas pendidikan.',
        'slug' => Str::slug('Kunjungan SMKN JENAWI JATENG ke SMKN 2 BUDURAN'),
        'published_at' => '2025-11-09 08:00:00',
        'category_id' => 2,
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news1.jpg',
        'content' => 'SMKN 2 Buduran menyambut kedatangan rombongan dari SMKN Jenawi Jateng. Kunjungan ini bertujuan untuk mempererat hubungan antar sekolah serta berbagi pengalaman dalam pengembangan pendidikan dan kegiatan siswa.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Kegiatan Magang Mahasiswa UMSIDA',
        'description' => 'Program magang mahasiswa Universitas Muhammadiyah Sidoarjo (UMSIDA) di SMKN 2 Buduran sebagai bentuk kerjasama antar lembaga pendidikan. Kegiatan ini memberikan pengalaman praktis kepada mahasiswa dalam dunia pendidikan kejuruan, sekaligus membantu proses pembelajaran di sekolah melalui transfer ilmu dan teknologi terbaru.',
        'slug' => Str::slug('Kegiatan Magang Mahasiswa UMSIDA'),
        'published_at' => '2025-08-12 10:30:00',
        'category_id' => 2, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news9.jpg',
        'content' => 'Sebagai bentuk kerjasama antar lembaga pendidikan, mahasiswa Universitas Muhammadiyah Sidoarjo (UMSIDA) melaksanakan kegiatan magang di SMKN 2 Buduran. Program ini bertujuan untuk memberikan pengalaman praktis di dunia pendidikan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Kegiatan Jumat "Berseri" Bersih Sehat Religi',
        'description' => 'Program rutin mingguan Jumat Berseri (Bersih, Sehat, Religi) di SMKN 2 Buduran yang melibatkan seluruh warga sekolah. Kegiatan ini bertujuan menciptakan lingkungan sekolah yang bersih dan sehat, sekaligus memperkuat nilai-nilai religius melalui kegiatan gotong royong, olahraga bersama, dan kajian keagamaan yang dilaksanakan setiap hari Jumat.',
        'slug' => Str::slug('Kegiatan Jumat Berseri Bersih Sehat Religi'),
        'published_at' => '2025-09-12 10:30:00',
        'category_id' => 2, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news2.jpg',
        'content' => 'Setiap hari Jumat, SMKN 2 Buduran melaksanakan kegiatan Jumat Berseri (Bersih, Sehat, Religi). Kegiatan ini melibatkan siswa, guru, dan staf dalam menjaga kebersihan sekolah, menjaga kesehatan, serta memperkuat nilai-nilai religius.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Kegiatan Pengimbasan Implementasi Pembelajaran Mendalam',
        'description' => 'Program pengimbasan dan sosialisasi implementasi pembelajaran mendalam di SMKN 2 Buduran untuk meningkatkan kualitas pendidikan kejuruan. Kegiatan ini melibatkan guru dan siswa dalam pelatihan pembelajaran berbasis proyek, penguatan kompetensi, dan pengembangan metodologi pembelajaran yang inovatif untuk menciptakan lulusan yang kompeten dan siap kerja.',
        'slug' => Str::slug('Kegiatan Pengimbasan Implementasi Pembelajaran Mendalam'),
        'published_at' => '2025-08-25 10:30:00',
        'category_id' => 2, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news4.jpg',
        'content' => 'Dalam rangka meningkatkan kualitas pembelajaran, SMKN 2 Buduran mengadakan kegiatan pengimbasan implementasi pembelajaran mendalam. Acara ini diikuti oleh guru dan siswa untuk menguatkan pemahaman serta praktik pembelajaran berbasis proyek.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Kegiatan "Pitulasan" Memperingati HUT RI yang ke 80',
        'description' => 'Perayaan Hari Ulang Tahun Kemerdekaan Republik Indonesia ke-80 melalui kegiatan Pitulasan di SMKN 2 Buduran. Acara meriah ini menampilkan berbagai lomba tradisional, upacara bendera, pentas seni, dan kegiatan kebersamaan lainnya yang bertujuan menumbuhkan rasa cinta tanah air dan semangat nasionalisme di kalangan siswa, guru, dan staf sekolah.',
        'slug' => Str::slug('Kegiatan Pitulasan Memperingati HUT RI yang ke 80'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 2, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news5.jpg',
        'content' => 'Dalam rangka memperingati Hari Ulang Tahun Republik Indonesia ke-80, SMKN 2 Buduran mengadakan kegiatan Pitulasan. Acara ini diisi dengan berbagai lomba, upacara, dan kegiatan kebersamaan yang penuh semangat kebangsaan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'School Road Show dan MOU bersama DUDI Mitra Usaha Pandu Artha',
        'description' => 'Program School Road Show dan penandatanganan Memorandum of Understanding (MOU) antara SMKN 2 Buduran dengan Dunia Usaha dan Dunia Industri (DUDI) Mitra Usaha Pandu Artha. Kerjasama ini bertujuan untuk membuka peluang magang, prakerin, dan penyerapan lulusan, sekaligus memastikan kurikulum sekolah selaras dengan kebutuhan industri untuk menciptakan link and match yang optimal.',
        'slug' => Str::slug('School Road Show dan MOU bersama DUDI Mitra Usaha Pandu Artha'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 2, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news15.jpg',
        'content' => 'SMKN 2 Buduran melaksanakan kegiatan School Road Show dan penandatanganan MOU dengan DUDI Mitra Usaha Pandu Artha untuk memperkuat kerjasama industri dan pendidikan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Kegiatan CITY FACE INDONESIA AKU MUDA AKU BEDA ( YOUTH MOVEMENT)',
        'description' => 'Partisipasi SMKN 2 Buduran dalam kegiatan City Face Indonesia dengan tema "Aku Muda Aku Beda" (Youth Movement). Program ini merupakan gerakan pemuda yang bertujuan mengembangkan kreativitas, inovasi, dan jiwa kepemimpinan siswa melalui berbagai kegiatan kompetitif dan kolaboratif. Acara ini juga menjadi wadah untuk menunjukkan potensi dan bakat siswa dalam berbagai bidang.',
        'slug' => Str::slug('Kegiatan CITY FACE INDONESIA AKU MUDA AKU BEDA YOUTH MOVEMENT'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 2, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news16.jpg',
        'content' => 'SMKN 2 Buduran berpartisipasi dalam kegiatan City Face Indonesia "Aku Muda Aku Beda" sebagai bagian dari youth movement untuk mengembangkan potensi dan kreativitas siswa.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Kegiatan Product Campaign dari Apetito',
        'description' => 'Kegiatan product campaign dan edukasi produk yang diselenggarakan oleh Apetito di SMKN 2 Buduran. Program ini memberikan wawasan kepada siswa mengenai industri makanan dan minuman, strategi pemasaran produk, serta peluang karir di bidang food and beverage. Kegiatan ini juga menjadi sarana pembelajaran praktis tentang dunia industri kuliner dan entrepreneurship bagi siswa jurusan terkait.',
        'slug' => Str::slug('Kegiatan Product Campaign dari Apetito'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 2, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news17.jpg',
        'content' => 'SMKN 2 Buduran mengadakan kegiatan product campaign dari Apetito yang memberikan edukasi dan wawasan industri makanan kepada siswa.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Guru Tamu Layanan Perbankan "Literasi Finansial"',
        'description' => 'Program guru tamu dari sektor perbankan dengan tema "Literasi Finansial" di SMKN 2 Buduran. Kegiatan ini bertujuan meningkatkan pemahaman siswa tentang pengelolaan keuangan, produk-produk perbankan, investasi, dan perencanaan finansial. Program edukasi ini sangat penting untuk mempersiapkan siswa menghadapi dunia kerja dan kehidupan mandiri dengan kemampuan mengelola keuangan yang baik.',
        'slug' => Str::slug('Guru Tamu Layanan Perbankan Literasi Finansial'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 2, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news18.jpg',
        'content' => 'SMKN 2 Buduran menghadirkan guru tamu dari sektor perbankan untuk memberikan edukasi literasi finansial kepada siswa dalam rangka meningkatkan pemahaman pengelolaan keuangan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],




     [
        'title' => 'Kerjasama dengan TIM Koramil dalam "Peningkatan Disiplin dan Latihan Baris Berbaris" dalam kegiatan MPLS 2025',
        'description' => 'SMKN 2 Buduran menjalin kerjasama strategis dengan TIM Koramil dalam program peningkatan disiplin siswa melalui latihan baris berbaris yang dilaksanakan dalam kegiatan Masa Pengenalan Lingkungan Sekolah (MPLS) 2025. Kegiatan ini bertujuan untuk membentuk karakter disiplin, tanggung jawab, dan jiwa kepemimpinan siswa baru melalui pelatihan militer dasar. Program ini melibatkan instruktur dari Koramil setempat yang memberikan pelatihan intensif tentang tata cara baris berbaris, kedisiplinan, dan nilai-nilai kebangsaan kepada seluruh siswa baru tahun ajaran 2025/2026.',
        'slug' => Str::slug('Kerjasama dengan TIM Koramil dalam Peningkatan Disiplin dan Latihan Baris Berbaris dalam kegiatan MPLS 2025'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 1, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news19.jpg',
        'content' => 'Dalam rangka memperingati Hari Ulang Tahun Republik Indonesia ke-80, SMKN 2 Buduran mengadakan kegiatan Pitulasan. Acara ini diisi dengan berbagai lomba, upacara, dan kegiatan kebersamaan yang penuh semangat kebangsaan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Kunjungan Tim Sarpras Dinas Provinsi Jatim ke SMKN 2 Buduran',
        'description' => 'Tim Sarana dan Prasarana (Sarpras) dari Dinas Pendidikan Provinsi Jawa Timur melakukan kunjungan kerja ke SMKN 2 Buduran untuk melakukan evaluasi dan monitoring terhadap kondisi infrastruktur sekolah. Kunjungan ini merupakan bagian dari program peningkatan kualitas sarana dan prasarana pendidikan di sekolah menengah kejuruan se-Jawa Timur. Tim akan melakukan assessment menyeluruh terhadap fasilitas pembelajaran, laboratorium, workshop, dan infrastruktur penunjang lainnya untuk memastikan standar kualitas pendidikan kejuruan terpenuhi dengan baik. Hasil evaluasi ini akan menjadi dasar penyusunan program pengembangan dan perbaikan fasilitas sekolah ke depan.',
        'slug' => Str::slug('Kunjungan Tim Sarpras Dinas Provinsi Jatim ke SMKN 2 Buduran'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 1, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news20.jpg',
        'content' => 'Dalam rangka memperingati Hari Ulang Tahun Republik Indonesia ke-80, SMKN 2 Buduran mengadakan kegiatan Pitulasan. Acara ini diisi dengan berbagai lomba, upacara, dan kegiatan kebersamaan yang penuh semangat kebangsaan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Sambut Tahun Ajaran Baru melalui Workshop Pembelajaran Mendalam Berbasis AI',
        'description' => 'SMKN 2 Buduran menyelenggarakan workshop inovatif tentang pembelajaran mendalam berbasis Artificial Intelligence (AI) sebagai persiapan menyambut tahun ajaran baru 2025/2026. Workshop ini dikhususkan bagi seluruh tenaga pendidik untuk meningkatkan kompetensi dalam memanfaatkan teknologi AI dalam proses pembelajaran. Materi workshop meliputi pengenalan teknologi AI dalam pendidikan, implementasi tools AI untuk pembelajaran interaktif, pengembangan konten digital berbasis AI, dan strategi integrasi AI dalam kurikulum SMK. Kegiatan ini merupakan upaya sekolah dalam menghadapi era digital dan mempersiapkan siswa dengan keterampilan abad 21 yang relevan dengan perkembangan teknologi terkini.',
        'slug' => Str::slug('Sambut Tahun Ajaran Baru melalui Workshop Pembelajaran Mendalam Berbasis AI'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 1, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news21.jpg',
        'content' => 'Dalam rangka memperingati Hari Ulang Tahun Republik Indonesia ke-80, SMKN 2 Buduran mengadakan kegiatan Pitulasan. Acara ini diisi dengan berbagai lomba, upacara, dan kegiatan kebersamaan yang penuh semangat kebangsaan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Monitoring dan Verifikasi SPMB DISABILITAS dari Dinas Provinsi Jawa Timur',
        'description' => 'Dinas Pendidikan Provinsi Jawa Timur melaksanakan kegiatan monitoring dan verifikasi Seleksi Penerimaan Mahasiswa Baru (SPMB) Disabilitas di SMKN 2 Buduran. Program ini merupakan implementasi dari kebijakan pendidikan inklusif yang memberikan kesempatan yang sama bagi siswa berkebutuhan khusus untuk mengakses pendidikan tinggi. Tim verifikasi melakukan pemeriksaan terhadap sistem dan prosedur penerimaan siswa disabilitas, fasilitas aksesibilitas, tenaga pendidik khusus, dan program pembelajaran adaptif. Kegiatan ini juga bertujuan untuk memastikan bahwa sekolah telah memenuhi standar layanan pendidikan yang ramah disabilitas sesuai dengan peraturan yang berlaku, serta memberikan rekomendasi perbaikan untuk meningkatkan kualitas layanan pendidikan inklusif.',
        'slug' => Str::slug('Monitoring dan Verifikasi SPMB DISABILITAS dari Dinas Provinsi Jawa Timur'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 1, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news22.jpg',
        'content' => 'Dalam rangka memperingati Hari Ulang Tahun Republik Indonesia ke-80, SMKN 2 Buduran mengadakan kegiatan Pitulasan. Acara ini diisi dengan berbagai lomba, upacara, dan kegiatan kebersamaan yang penuh semangat kebangsaan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Social Leader Movement Project bersama dengan Alumni / Mahasiswa UPN',
        'description' => 'SMKN 2 Buduran berkolaborasi dengan para alumni dan mahasiswa Universitas Pembangunan Nasional (UPN) dalam melaksanakan Social Leader Movement Project, sebuah program pemberdayaan kepemimpinan sosial bagi siswa. Project ini dirancang untuk mengembangkan jiwa kepemimpinan, kepekaan sosial, dan kemampuan problem solving siswa melalui kegiatan-kegiatan sosial kemasyarakatan. Para alumni dan mahasiswa UPN berperan sebagai mentor dan fasilitator dalam berbagai kegiatan seperti bakti sosial, edukasi masyarakat, dan program pengembangan diri. Melalui project ini, siswa diharapkan dapat memahami peran mereka sebagai agent of change dalam masyarakat dan memiliki kemampuan untuk memberikan kontribusi positif bagi lingkungan sekitar. Program ini juga memperkuat jaringan alumni dan menciptakan sinergi antara dunia pendidikan menengah dan perguruan tinggi.',
        'slug' => Str::slug('Social Leader Movement Project bersama dengan Alumni Mahasiswa UPN'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 1, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news23.jpg',
        'content' => 'Dalam rangka memperingati Hari Ulang Tahun Republik Indonesia ke-80, SMKN 2 Buduran mengadakan kegiatan Pitulasan. Acara ini diisi dengan berbagai lomba, upacara, dan kegiatan kebersamaan yang penuh semangat kebangsaan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Kerjasama 3 Helix (DUDI, UBAYA dan SMKN 2 Buduran) "Kuliah Sambil Kerja"',
        'description' => 'SMKN 2 Buduran menjalin kerjasama strategis model Triple Helix dengan Dunia Usaha Dunia Industri (DUDI) dan Universitas Surabaya (UBAYA) dalam program inovatif "Kuliah Sambil Kerja". Program ini memungkinkan siswa untuk melanjutkan pendidikan ke jenjang perguruan tinggi sambil tetap bekerja di industri yang relevan dengan bidang keahlian mereka. Kerjasama tiga pihak ini menciptakan ekosistem pendidikan yang terintegrasi antara SMK, universitas, dan dunia industri. Siswa akan mendapatkan pengalaman kerja nyata di perusahaan mitra sambil menempuh pendidikan tinggi dengan sistem pembelajaran fleksibel. Model kerjasama ini diharapkan dapat meningkatkan daya saing lulusan, memberikan jaminan karir yang jelas, serta memperkuat link and match antara dunia pendidikan dengan kebutuhan industri di era revolusi industri 4.0.',
        'slug' => Str::slug('Kerjasama 3 Helix DUDI UBAYA dan SMKN 2 Buduran Kuliah Sambil Kerja'),
        'published_at' => '2025-08-27 10:30:00',
        'category_id' => 1, 
        'thumbnail' => 'https://kmzmzmrdwbaaibcgqowh.supabase.co/storage/v1/object/public/images/news/news24.jpg',
        'content' => 'Dalam rangka memperingati Hari Ulang Tahun Republik Indonesia ke-80, SMKN 2 Buduran mengadakan kegiatan Pitulasan. Acara ini diisi dengan berbagai lomba, upacara, dan kegiatan kebersamaan yang penuh semangat kebangsaan.',
        'created_at' => now(),
        'updated_at' => now(),
    ],

]

        );
    }
}
